name: "deploy neovimcraft cron"

on:
  workflow_dispatch:

#  schedule:
#  - cron: "0 */6 * * *"

env:
  GITHUB_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  GITHUB_USERNAME: ${{secrets.USERNAME}}
  SRHT_ACCESS_TOKEN: ${{secrets.SRHT_ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "~1.42"
    - run: make scrape
    - run: make build
    - run: ls -lah ./public

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: upload to pgs
      uses: picosh/pgs-action@v3
      with:
        user: erock
        key: ${{ secrets.PRIVATE_KEY }}
        src: './public/'
        project: "neovimcraft-${{ steps.vars.outputs.sha_short }}"
        promote: "neovimcraft"
        retain: "neovimcraft-"
        retain_num: 1
